exports.NOTIFICATION_TYPES = {
    "COMMERCE": "COMMERCE",
    "ASK": "ASK",
}

exports.CONVERSATION_STATUS = {
    "PENDING": "PENDING",
    "ACCEPTED": "ACCEPTED",
    "CLOSED": "CLOSED"
}

exports.APPOINTMENT_TYPE = {
    "MAINTENANCE": 120,
    "ESSAY-CITY": 60,
    "ESSAY-OFFROAD": 60,
    "ESSAY-SPORT": 60,
}
