exports.NOTIFICATION_TYPES = {
    "COMMERCE": "COMMERCE",
    "ASK": "ASK",
}

exports.CONVERSATION_STATUS = {
    "PENDING": "PENDING",
    "ACCEPTED": "ACCEPTED",
    "CLOSED": "CLOSED"
}

exports.APPOINTMENT_TYPE = {
    "ESSAY": 30,
    "MAINTENANCE": 120,
    "REVISION": 60
}
